apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  namespace: kube-system
  name: argocd-apps
spec:
  targetNamespace: argocd
  createNamespace: true
  version: 2.0.2
  chart: argocd-apps
  repo: https://argoproj.github.io/argo-helm
  valuesContent: |-
    applications:
      myblog:
        namespace: argocd
        project: default
        source:
          path: helm
          repoURL: git@github.com:Assstra/cybersecurity_writeups.git
          targetRevision: HEAD
          helm:
            valueFiles:
              - values.yaml
        destination:
          namespace: myblog
          server: https://kubernetes.default.svc
        syncPolicy:
          automated:
            prune: true
            selfHeal: false
          syncOptions:
            - CreateNamespace=true