apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: argocd
  namespace: kube-system
spec:
  targetNamespace: argocd
  createNamespace: true
  version: 7.7.17
  chart: argo-cd
  repo: https://argoproj.github.io/argo-helm

  valuesContent: |-
    crds:
      install: true
    global:
      domain: argocd.araimbault.com
