---
- name: Deploy Aggregator Service
  hosts: all
  become: true
  vars:
    app_name: aggregator
    app_port: 3000
    noun_provider_url: "http://localhost:3001"
    verb_provider_url: "http://localhost:3002"
    node_version: "16.x"  # Update to the version you need
    app_dir: "/opt/aggregator"

  tasks:
    - name: Install prerequisites
      apt:
        name:
          - curl
          - gnupg
        state: present
        update_cache: true

    - name: Add Node.js repository
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_{{ node_version }} | bash -
      args:
        executable: /bin/bash

    - name: Install Node.js
      apt:
        name: nodejs
        state: present

    - name: Create application directory
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Copy application code
      copy:
        src: ./aggregator
        dest: "{{ app_dir }}"
        owner: www-data
        group: www-data"
        mode: '0755'

    - name: Install application dependencies
      command: npm install
      args:
        chdir: "{{ app_dir }}"

    - name: Create environment file
      copy:
        dest: "{{ app_dir }}/.env"
        content: |
          PORT={{ app_port }}
          VERB_PROVIDER_URL={{ verb_provider_url }}
          NOUN_PROVIDER_URL={{ noun_provider_url }}
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Create systemd service file
      copy:
        dest: /etc/systemd/system/{{ app_name }}.service
        content: |
          [Unit]
          Description=Aggregator Service
          After=network.target

          [Service]
          EnvironmentFile={{ app_dir }}/.env
          ExecStart=/usr/bin/node {{ app_dir }}/index.js
          WorkingDirectory={{ app_dir }}
          Restart=always
          User=www-data
          Group=www-data

          [Install]
          WantedBy=multi-user.target
        owner: root
        group: root
        mode: '0644'

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Enable and start service
      systemd:
        name: "{{ app_name }}"
        enabled: true
        state: started
