---
- name: Deploy K3s
  hosts: localhost
  become: true

  vars:
    secret_name: ghcr-login-secret
    namespace: myblog

  tasks:
    - name: Create the k3s server manifests directory
      file:
        path: /var/lib/rancher/k3s/server/manifests
        state: directory
        mode: 0755

    - name: Copy the cert-manager Helm chart file
      copy:
        src: cert-manager-helm-chart.yml
        dest: /var/lib/rancher/k3s/server/manifests/cert-manager.yaml
        mode: 0600

    - name: Create myblog secret file
      copy:
        dest: /var/lib/rancher/k3s/server/manifests/myblog-secret.yaml
        content: |
          apiVersion: v1
          kind: Namespace
          metadata:
            name: {{ namespace }}
          ---
          apiVersion: v1
          kind: Secret
          metadata:
            name: {{ secret_name }}
            namespace: {{ namespace }}
          type: kubernetes.io/dockerconfigjson
          stringData:
            .dockerconfigjson: >-
              {
                "auths": {
                  "ghcr.io": {
                    "username": "{{ github_username }}",
                    "password": "{{ github_token }}",
                    "email": "{{ github_email }}"
                  }
                }
              }
        mode: 0600

    - name: Copy the argocd Helm chart file
      copy:
        src: argocd-helm-chart.yml
        dest: /var/lib/rancher/k3s/server/manifests/argocd.yaml
        mode: 0600

    - name: Copy the traefik Helm chart file
      copy:
        src: traefik-helm-chart.yml
        dest: /var/lib/rancher/k3s/server/manifests/traefik.yaml
        mode: 0600
    
    - name: Copy the application Helm chart file
      copy:
        src: argocd-app.yml
        dest: /var/lib/rancher/k3s/server/manifests/argocd-app.yaml
        mode: 0600

    - name: Install k3s
      shell: curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="server --disable=traefik" sh -

    - name: Apply Gateway API standard installation
      ansible.builtin.command:
        cmd: kubectl apply -f "https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.0.0/standard-install.yaml"

    - name: Restart cert-manager deployment
      ansible.builtin.command:
        cmd: kubectl rollout restart deployment cert-manager -n cert-manager

    - name: Apply Traefik Kubernetes Gateway RBAC
      ansible.builtin.command:
        cmd: kubectl apply -f "https://raw.githubusercontent.com/traefik/traefik/v3.3/docs/content/reference/dynamic-configuration/kubernetes-gateway-rbac.yml"
    
    - name: Restart traefik deployment
      ansible.builtin.command:
        cmd: kubectl rollout restart deployment traefik -n traefik
