---
- name: Deploy K3s
  hosts: localhost
  become: true

  vars:
    secret_name: ghcr-login-secret
    namespace: myblog

  tasks:
    - name: Create the k3s server manifests directory
      file:
        path: /var/lib/rancher/k3s/server/manifests
        state: directory
        mode: 0755

    # - name: Copy the cert-manager Helm chart file
    #   copy:
    #     src: cert-manager-helm-chart.yml
    #     dest: /var/lib/rancher/k3s/server/manifests/cert-manager.yaml
    #     mode: 0600

    - name: Create myblog secret file
      copy:
        dest: /var/lib/rancher/k3s/server/manifests/myblog-secret.yaml
        content: |
          apiVersion: v1
          kind: Namespace
          metadata:
            name: {{ namespace }}
          ---
          apiVersion: v1
          kind: Secret
          metadata:
            name: {{ secret_name }}
            namespace: {{ namespace }}
          type: kubernetes.io/dockerconfigjson
          stringData:
            .dockerconfigjson: >-
              {
                "auths": {
                  "ghcr.io": {
                    "username": "{{ github_username }}",
                    "password": "{{ github_token }}",
                    "email": "{{ github_email }}"
                  }
                }
              }
        mode: 0600

    - name: Copy the argocd Helm chart file
      copy:
        src: argocd-helm-chart.yml
        dest: /var/lib/rancher/k3s/server/manifests/argocd.yaml
        mode: 0600
    
    - name: Copy the application Helm chart file
      copy:
        src: argocd-app.yml
        dest: /var/lib/rancher/k3s/server/manifests/argocd-app.yaml
        mode: 0600

    - name: Install k3s
      shell: curl -sfL https://get.k3s.io | sh -

    - name: Print the kubeconfig file
      shell: cat /etc/rancher/k3s/k3s.yaml

# TODO : add a kubeconfig env value to get .kube/config for debian