---
- name: Deploy Random verb Service
  hosts: localhost
  become: true
  vars:
    app_name: verb-provider
    word_type: verb
    node_version: "23"
    app_dir: "/opt/app/sample_app/verb-provider"

  tasks:
    - name: Install prerequisites
      apt:
        name:
          - curl
          - gnupg
        state: present
        update_cache: true

    - name: Add Node.js repository
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_{{ node_version }} | bash -
      args:
        executable: /bin/bash

    - name: Install Node.js
      apt:
        name: nodejs
        state: present

    - name: Install npm
      apt:
        name: npm
        state: present

    - name: Example clone of a single branch
      git:
        repo: https://github.com/Assstra/kube_security.git
        dest: /opt/app
        single_branch: yes
        version: main

    - name: Install application dependencies
      command: npm install
      args:
        chdir: "{{ app_dir }}"

    - name: Create environment file
      copy:
        dest: "{{ app_dir }}/.env"
        content: |
          PORT={{ app_port }}
          WORD_TYPE={{ word_type }}
        owner: root
        group: root
        mode: '0644'

    - name: Create systemd service file
      copy:
        dest: /etc/systemd/system/{{ app_name }}.service
        content: |
          [Unit]
          Description=Verb provider Service
          After=network.target

          [Service]
          EnvironmentFile={{ app_dir }}/.env
          ExecStart=/usr/bin/node {{ app_dir }}/index.js
          WorkingDirectory={{ app_dir }}
          Restart=always
          User=root
          Group=root

          [Install]
          WantedBy=multi-user.target
        owner: root
        group: root
        mode: '0644'

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Enable and start service
      systemd:
        name: "{{ app_name }}"
        enabled: true
        state: started
